# Form implementation generated from reading ui file 'assets/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(671, 360)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_pick_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.input_pick_button.setGeometry(QtCore.QRect(60, 60, 161, 31))
        self.input_pick_button.setObjectName("input_pick_button")
        self.output_pick_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.output_pick_button.setGeometry(QtCore.QRect(60, 110, 161, 31))
        self.output_pick_button.setObjectName("output_pick_button")
        self.run_workflow_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.run_workflow_button.setGeometry(QtCore.QRect(60, 260, 161, 31))
        self.run_workflow_button.setObjectName("run_workflow_button")
        self.input_file_path_line_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_file_path_line_edit.setGeometry(QtCore.QRect(230, 60, 381, 31))
        self.input_file_path_line_edit.setObjectName("input_file_path_line_edit")
        self.output_file_path_line_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.output_file_path_line_edit.setGeometry(QtCore.QRect(230, 110, 381, 31))
        self.output_file_path_line_edit.setObjectName("output_file_path_line_edit")
        self.state_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.state_label.setGeometry(QtCore.QRect(230, 260, 381, 31))
        self.state_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.state_label.setObjectName("state_label")
        self.groups_spinbox = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.groups_spinbox.setGeometry(QtCore.QRect(230, 160, 41, 31))
        self.groups_spinbox.setProperty("value", 4)
        self.groups_spinbox.setObjectName("groups_spinbox")
        self.iterations_spinbox = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.iterations_spinbox.setGeometry(QtCore.QRect(230, 210, 41, 31))
        self.iterations_spinbox.setProperty("value", 3)
        self.iterations_spinbox.setObjectName("iterations_spinbox")
        self.groups_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.groups_label.setGeometry(QtCore.QRect(60, 160, 161, 31))
        self.groups_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groups_label.setObjectName("groups_label")
        self.iterations_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.iterations_label.setGeometry(QtCore.QRect(60, 210, 161, 31))
        self.iterations_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.iterations_label.setObjectName("iterations_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 671, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.input_pick_button.setText(_translate("MainWindow", "Wähle Eingabedatei aus"))
        self.output_pick_button.setText(_translate("MainWindow", "Wähle Ausgabedatei aus"))
        self.run_workflow_button.setText(_translate("MainWindow", "Start!"))
        self.state_label.setText(_translate("MainWindow", "Status: Waiting..."))
        self.groups_label.setText(_translate("MainWindow", "Anzahl Gruppen:"))
        self.iterations_label.setText(_translate("MainWindow", "Anzahl Iterationen: "))
