name: MyPy

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Typecheck with mypy
        run: |
          python -m pip install -e '.[dev]' --upgrade pip
          mypy --python-version ${{ matrix.python-version }} -p src --implicit-optional --warn-unreachable --enable-incomplete-feature=NewGenericSyntax
